### ISSUE TITLE
About package `nod`

### ISSUE THREAD

**Issue by taljacob2** [taljacob2/colman-advanced-web-apps-ex-1#31]
> @mevo0108 Can you explain what is this package used for?
> I assume is probably a mistake.
> 
> If so please revert this commit.
> 
> ```
> git revert c8ac3dc
> git push
> ```
>  

 _Originally posted by @taljacob2 in [c8ac3dc](https://github.com/taljacob2/colman-advanced-web-apps-ex-1/commit/c8ac3dc2b664f870a1d653c6078d0bb1b36c2801#r149853007)_

**Comment by mevo0108** [comment]
It probably got added when I reinstalled Nodemon.
In any case, I'm trying to do a REVERT, but I can't seem to gain control of the terminal there and add a COMMENT.
It shouldn't interfere with the code

**Comment by taljacob2** [comment]
I can help with that if you want

**Comment by mevo0108** [comment]
You can erase that if you want I will check if it's working without it

בתאריך יום ג׳, 3 בדצמ׳ 2024, 16:11, מאת Tal Jacob ***@***.***

**Comment by taljacob2** [comment]
Fixed in c972252c0f185ec3c346e46285029f95f85e4d83
